package flat.checker

import com.typesafe.scalalogging.LazyLogging
import flat.checker.ast.{Expr, FunDef, Module, Var}
import flat.{ExtractConfig, checker}
import io.github.cvc5
import io.github.cvc5.Kind

import scala.collection.mutable.ListBuffer

/** SMT Formula Extractor */
class Extractor(using config: ExtractConfig) extends LazyLogging:
  /** Extracts the SMT formulae generated from the given `module` compiled from the source in `path`.
   * Saves as SMT-LIB files. */
  def extract(module: Module, path: os.Path): Unit =
    val relPath = (path / "..").relativeTo(config.input)
    val outDir = config.output / relPath / path.baseName
    module.body.foreach(s => extract(s.asInstanceOf[FunDef], outDir))

  private def extract(funDef: FunDef, outDir: os.Path): Unit =
    val lines = ListBuffer.empty[String]
    lines ++= head
    val vc = VCGenerator.generate(funDef)
    val varCtx = VarCtx.from(funDef)
    val encoder = new SMTEncoder(using varCtx, true)
    val term = encode(vc)(using encoder)
    for x -> t <- encoder.getCtx do
      val name = x match
        case Var(x) => x
        case _ => x.toString.replaceAll("\\s+", "_")
      lines += declare(name, t.getSort)
    lines ++= prove(term)
    lines += "(exit)"
    val outPath = outDir / s"${funDef.name}-full.smt2"
    os.write.over(outPath, lines.mkString("\n"), createFolders = true)
    logger.info("Written: {}", outPath)

    if config.multiGoals then // multi-goals
      for (hs -> c, i) <- split(vc).zipWithIndex do
        val lines = ListBuffer.empty[String]
        val encoder = new SMTEncoder(using varCtx, true)
        val assumptions = hs.map(encoder.encodeExpr)
        val conclusion = encoder.encodeExpr(c)
        for x -> t <- encoder.getCtx do
          val name = x match
            case Var(x) => x
            case _ => x.toString.replaceAll("\\s+", "_")
          lines += declare(name, t.getSort)
        for term <- assumptions do
          lines += assume(term)
        lines ++= prove(conclusion)
        lines += "(exit)"
        val outPath = outDir / s"${funDef.name}-goal-${i + 1}.smt2"
        os.write.over(outPath, lines.mkString("\n"), createFolders = true)
        logger.info("Written: {}", outPath)

  private def encode(vc: VC)(using smtEncoder: SMTEncoder): cvc5.Term = vc match
    case VCTrue => smtEncoder.tm.mkTrue
    case VCImp(b, vc) =>
      val left = smtEncoder.encodeExpr(b)
      val right = encode(vc)
      smtEncoder.tm.mkTerm(Kind.IMPLIES, left, right)
    case VCGroup(sides, mains) =>
      val conjuncts = sides.map(encode) ++ mains.map(encode)
      if conjuncts.isEmpty then smtEncoder.tm.mkTrue else conjuncts.reduce(_.andTerm(_))
    case VCInfer(_) =>
      logger.warn("ignore VCInfer")
      smtEncoder.tm.mkTrue
    case goal: VCGoal => smtEncoder.encodeExpr(goal.cond)

  private def split(vc: VC): List[(List[Expr], Expr)] = vc match
    case VCTrue => Nil
    case VCImp(b, vc) => for hs -> c <- split(vc) yield (b :: hs) -> c
    case VCGroup(sides, mains) => sides.flatMap(split) ++ mains.flatMap(split)
    case VCInfer(_) =>
      logger.warn("ignore VCInfer")
      Nil
    case goal: VCGoal => List(Nil -> goal.cond)

  private inline def head = List(
    "; Generated by FLAT-Checker",
    "(set-logic ALL)"
  )

  private inline def declare(name: String, sort: cvc5.Sort): String = s"(declare-const $name $sort)"

  private inline def assume(term: cvc5.Term): String = s"(assert $term)"

  private inline def prove(term: cvc5.Term): List[String] = List(
    s"(assert ${term.notTerm})",
    "(check-sat)"
  )
