name: CI
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
      - name: Setup sbt
        uses: sbt/setup-sbt@v1
        with:
          sbt-runner-version: 1.10.0
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.12
      - name: Install cvc5
        run: python scripts/install_cvc5.py
      - name: Build & Test
        run: sbt -v +test
      - name: Check example file
        run: sbt assembly && ./flat-checker examples/a_star.py